-- ==========================================================
-- TPC-DS schema for PostgreSQL (auto-generated by setup_tpcds.py)
-- DO NOT edit by hand — re-run the setup script.
-- ==========================================================

DROP TABLE IF EXISTS catalog_returns CASCADE;
DROP TABLE IF EXISTS catalog_sales CASCADE;
DROP TABLE IF EXISTS web_returns CASCADE;
DROP TABLE IF EXISTS web_sales CASCADE;
DROP TABLE IF EXISTS store_returns CASCADE;
DROP TABLE IF EXISTS store_sales CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS catalog_page CASCADE;
DROP TABLE IF EXISTS call_center CASCADE;
DROP TABLE IF EXISTS store CASCADE;
DROP TABLE IF EXISTS web_page CASCADE;
DROP TABLE IF EXISTS web_site CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS time_dim CASCADE;
DROP TABLE IF EXISTS date_dim CASCADE;
DROP TABLE IF EXISTS customer_address CASCADE;
DROP TABLE IF EXISTS customer_demographics CASCADE;
DROP TABLE IF EXISTS household_demographics CASCADE;
DROP TABLE IF EXISTS promotion CASCADE;
DROP TABLE IF EXISTS warehouse CASCADE;
DROP TABLE IF EXISTS reason CASCADE;
DROP TABLE IF EXISTS ship_mode CASCADE;
DROP TABLE IF EXISTS income_band CASCADE;

-- ----- income_band -----
CREATE TABLE income_band (
    ib_income_band_sk            BIGINT,
    ib_lower_bound               BIGINT,
    ib_upper_bound               INTEGER
);

-- ----- ship_mode -----
CREATE TABLE ship_mode (
    sm_ship_mode_sk              BIGINT,
    sm_ship_mode_id              TEXT,
    sm_type                      TEXT,
    sm_code                      TEXT,
    sm_carrier                   TEXT,
    sm_contract                  TEXT
);

-- ----- reason -----
CREATE TABLE reason (
    r_reason_sk                  BIGINT,
    r_reason_id                  TEXT,
    r_reason_desc                TEXT
);

-- ----- warehouse -----
CREATE TABLE warehouse (
    w_warehouse_sk               BIGINT,
    w_warehouse_id               TEXT,
    w_warehouse_name             TEXT,
    w_warehouse_sq_ft            BIGINT,
    w_street_number              TEXT,
    w_street_name                TEXT,
    w_street_type                TEXT,
    w_suite_number               TEXT,
    w_city                       TEXT,
    w_county                     TEXT,
    w_state                      TEXT,
    w_zip                        TEXT,
    w_country                    TEXT,
    w_gmt_offset                 DECIMAL(5,2)
);

-- ----- promotion -----
CREATE TABLE promotion (
    p_promo_sk                   BIGINT,
    p_promo_id                   TEXT,
    p_start_date_sk              BIGINT,
    p_end_date_sk                BIGINT,
    p_item_sk                    BIGINT,
    p_cost                       DECIMAL(15,2),
    p_response_target            BIGINT,
    p_promo_name                 TEXT,
    p_channel_dmail              TEXT,
    p_channel_email              TEXT,
    p_channel_catalog            TEXT,
    p_channel_tv                 TEXT,
    p_channel_radio              TEXT,
    p_channel_press              TEXT,
    p_channel_event              TEXT,
    p_channel_demo               TEXT,
    p_channel_details            TEXT,
    p_purpose                    TEXT,
    p_discount_active            TEXT
);

-- ----- household_demographics -----
CREATE TABLE household_demographics (
    hd_demo_sk                   BIGINT,
    hd_income_band_sk            BIGINT,
    hd_buy_potential             TEXT,
    hd_dep_count                 BIGINT,
    hd_vehicle_count             INTEGER
);

-- ----- customer_demographics -----
CREATE TABLE customer_demographics (
    cd_demo_sk                   BIGINT,
    cd_gender                    TEXT,
    cd_marital_status            TEXT,
    cd_education_status          TEXT,
    cd_purchase_estimate         BIGINT,
    cd_credit_rating             TEXT,
    cd_dep_count                 BIGINT,
    cd_dep_employed_count        BIGINT,
    cd_dep_college_count         INTEGER
);

-- ----- customer_address -----
CREATE TABLE customer_address (
    ca_address_sk                BIGINT,
    ca_address_id                TEXT,
    ca_street_number             TEXT,
    ca_street_name               TEXT,
    ca_street_type               TEXT,
    ca_suite_number              TEXT,
    ca_city                      TEXT,
    ca_county                    TEXT,
    ca_state                     TEXT,
    ca_zip                       TEXT,
    ca_country                   TEXT,
    ca_gmt_offset                DECIMAL(5,2),
    ca_location_type             TEXT
);

-- ----- date_dim -----
CREATE TABLE date_dim (
    d_date_sk                    BIGINT,
    d_date_id                    TEXT,
    d_date                       DATE,
    d_month_seq                  BIGINT,
    d_week_seq                   BIGINT,
    d_quarter_seq                BIGINT,
    d_year                       BIGINT,
    d_dow                        BIGINT,
    d_moy                        BIGINT,
    d_dom                        BIGINT,
    d_qoy                        BIGINT,
    d_fy_year                    BIGINT,
    d_fy_quarter_seq             BIGINT,
    d_fy_week_seq                BIGINT,
    d_day_name                   TEXT,
    d_quarter_name               TEXT,
    d_holiday                    TEXT,
    d_weekend                    TEXT,
    d_following_holiday          TEXT,
    d_first_dom                  BIGINT,
    d_last_dom                   BIGINT,
    d_same_day_ly                BIGINT,
    d_same_day_lq                BIGINT,
    d_current_day                TEXT,
    d_current_week               TEXT,
    d_current_month              TEXT,
    d_current_quarter            TEXT,
    d_current_year               TEXT
);

-- ----- time_dim -----
CREATE TABLE time_dim (
    t_time_sk                    BIGINT,
    t_time_id                    TEXT,
    t_time                       BIGINT,
    t_hour                       BIGINT,
    t_minute                     BIGINT,
    t_second                     BIGINT,
    t_am_pm                      TEXT,
    t_shift                      TEXT,
    t_sub_shift                  TEXT,
    t_meal_time                  TEXT
);

-- ----- item -----
CREATE TABLE item (
    i_item_sk                    BIGINT,
    i_item_id                    TEXT,
    i_rec_start_date             DATE,
    i_rec_end_date               DATE,
    i_item_desc                  TEXT,
    i_current_price              DECIMAL(7,2),
    i_wholesale_cost             DECIMAL(7,2),
    i_brand_id                   BIGINT,
    i_brand                      TEXT,
    i_class_id                   BIGINT,
    i_class                      TEXT,
    i_category_id                BIGINT,
    i_category                   TEXT,
    i_manufact_id                BIGINT,
    i_manufact                   TEXT,
    i_size                       TEXT,
    i_formulation                TEXT,
    i_color                      TEXT,
    i_units                      TEXT,
    i_container                  TEXT,
    i_manager_id                 BIGINT,
    i_product_name               TEXT
);

-- ----- web_site -----
CREATE TABLE web_site (
    web_site_sk                  BIGINT,
    web_site_id                  TEXT,
    web_rec_start_date           DATE,
    web_rec_end_date             DATE,
    web_name                     TEXT,
    web_open_date_sk             BIGINT,
    web_close_date_sk            BIGINT,
    web_class                    TEXT,
    web_manager                  TEXT,
    web_mkt_id                   BIGINT,
    web_mkt_class                TEXT,
    web_mkt_desc                 TEXT,
    web_market_manager           TEXT,
    web_company_id               BIGINT,
    web_company_name             TEXT,
    web_street_number            TEXT,
    web_street_name              TEXT,
    web_street_type              TEXT,
    web_suite_number             TEXT,
    web_city                     TEXT,
    web_county                   TEXT,
    web_state                    TEXT,
    web_zip                      TEXT,
    web_country                  TEXT,
    web_gmt_offset               DECIMAL(5,2),
    web_tax_percentage           DECIMAL(5,2)
);

-- ----- web_page -----
CREATE TABLE web_page (
    wp_web_page_sk               BIGINT,
    wp_web_page_id               TEXT,
    wp_rec_start_date            DATE,
    wp_rec_end_date              DATE,
    wp_creation_date_sk          BIGINT,
    wp_access_date_sk            BIGINT,
    wp_autogen_flag              TEXT,
    wp_customer_sk               BIGINT,
    wp_url                       TEXT,
    wp_type                      TEXT,
    wp_char_count                BIGINT,
    wp_link_count                BIGINT,
    wp_image_count               BIGINT,
    wp_max_ad_count              INTEGER
);

-- ----- store -----
CREATE TABLE store (
    s_store_sk                   BIGINT,
    s_store_id                   TEXT,
    s_rec_start_date             DATE,
    s_rec_end_date               DATE,
    s_closed_date_sk             BIGINT,
    s_store_name                 TEXT,
    s_number_employees           BIGINT,
    s_floor_space                BIGINT,
    s_hours                      TEXT,
    s_manager                    TEXT,
    s_market_id                  BIGINT,
    s_geography_class            TEXT,
    s_market_desc                TEXT,
    s_market_manager             TEXT,
    s_division_id                BIGINT,
    s_division_name              TEXT,
    s_company_id                 BIGINT,
    s_company_name               TEXT,
    s_street_number              TEXT,
    s_street_name                TEXT,
    s_street_type                TEXT,
    s_suite_number               TEXT,
    s_city                       TEXT,
    s_county                     TEXT,
    s_state                      TEXT,
    s_zip                        TEXT,
    s_country                    TEXT,
    s_gmt_offset                 DECIMAL(5,2),
    s_tax_percentage             DECIMAL(5,2)
);

-- ----- call_center -----
CREATE TABLE call_center (
    cc_call_center_sk            BIGINT,
    cc_call_center_id            TEXT,
    cc_rec_start_date            DATE,
    cc_rec_end_date              DATE,
    cc_closed_date_sk            BIGINT,
    cc_open_date_sk              BIGINT,
    cc_name                      TEXT,
    cc_class                     TEXT,
    cc_employees                 BIGINT,
    cc_sq_ft                     BIGINT,
    cc_hours                     TEXT,
    cc_manager                   TEXT,
    cc_mkt_id                    BIGINT,
    cc_mkt_class                 TEXT,
    cc_mkt_desc                  TEXT,
    cc_market_manager            TEXT,
    cc_division                  BIGINT,
    cc_division_name             TEXT,
    cc_company                   BIGINT,
    cc_company_name              TEXT,
    cc_street_number             TEXT,
    cc_street_name               TEXT,
    cc_street_type               TEXT,
    cc_suite_number              TEXT,
    cc_city                      TEXT,
    cc_county                    TEXT,
    cc_state                     TEXT,
    cc_zip                       TEXT,
    cc_country                   TEXT,
    cc_gmt_offset                DECIMAL(5,2),
    cc_tax_percentage            DECIMAL(5,2)
);

-- ----- catalog_page -----
CREATE TABLE catalog_page (
    cp_catalog_page_sk           BIGINT,
    cp_catalog_page_id           TEXT,
    cp_start_date_sk             BIGINT,
    cp_end_date_sk               BIGINT,
    cp_department                TEXT,
    cp_catalog_number            BIGINT,
    cp_catalog_page_number       BIGINT,
    cp_description               TEXT,
    cp_type                      TEXT
);

-- ----- customer -----
CREATE TABLE customer (
    c_customer_sk                BIGINT,
    c_customer_id                TEXT,
    c_current_cdemo_sk           BIGINT,
    c_current_hdemo_sk           BIGINT,
    c_current_addr_sk            BIGINT,
    c_first_shipto_date_sk       BIGINT,
    c_first_sales_date_sk        BIGINT,
    c_salutation                 TEXT,
    c_first_name                 TEXT,
    c_last_name                  TEXT,
    c_preferred_cust_flag        TEXT,
    c_birth_day                  BIGINT,
    c_birth_month                BIGINT,
    c_birth_year                 BIGINT,
    c_birth_country              TEXT,
    c_login                      TEXT,
    c_email_address              TEXT,
    c_last_review_date_sk        INTEGER
);

-- ----- inventory -----
CREATE TABLE inventory (
    inv_date_sk                  BIGINT,
    inv_item_sk                  BIGINT,
    inv_warehouse_sk             BIGINT,
    inv_quantity_on_hand         INTEGER
);

-- ----- store_sales -----
CREATE TABLE store_sales (
    ss_sold_date_sk              BIGINT,
    ss_sold_time_sk              BIGINT,
    ss_item_sk                   BIGINT,
    ss_customer_sk               BIGINT,
    ss_cdemo_sk                  BIGINT,
    ss_hdemo_sk                  BIGINT,
    ss_addr_sk                   BIGINT,
    ss_store_sk                  BIGINT,
    ss_promo_sk                  BIGINT,
    ss_ticket_number             BIGINT,
    ss_quantity                  BIGINT,
    ss_wholesale_cost            DECIMAL(7,2),
    ss_list_price                DECIMAL(7,2),
    ss_sales_price               DECIMAL(7,2),
    ss_ext_discount_amt          DECIMAL(7,2),
    ss_ext_sales_price           DECIMAL(7,2),
    ss_ext_wholesale_cost        DECIMAL(7,2),
    ss_ext_list_price            DECIMAL(7,2),
    ss_ext_tax                   DECIMAL(7,2),
    ss_coupon_amt                DECIMAL(7,2),
    ss_net_paid                  DECIMAL(7,2),
    ss_net_paid_inc_tax          DECIMAL(7,2),
    ss_net_profit                DECIMAL(7,2)
);

-- ----- store_returns -----
CREATE TABLE store_returns (
    sr_returned_date_sk          BIGINT,
    sr_return_time_sk            BIGINT,
    sr_item_sk                   BIGINT,
    sr_customer_sk               BIGINT,
    sr_cdemo_sk                  BIGINT,
    sr_hdemo_sk                  BIGINT,
    sr_addr_sk                   BIGINT,
    sr_store_sk                  BIGINT,
    sr_reason_sk                 BIGINT,
    sr_ticket_number             BIGINT,
    sr_return_quantity           BIGINT,
    sr_return_amt                DECIMAL(7,2),
    sr_return_tax                DECIMAL(7,2),
    sr_return_amt_inc_tax        DECIMAL(7,2),
    sr_fee                       DECIMAL(7,2),
    sr_return_ship_cost          DECIMAL(7,2),
    sr_refunded_cash             DECIMAL(7,2),
    sr_reversed_charge           DECIMAL(7,2),
    sr_store_credit              DECIMAL(7,2),
    sr_net_loss                  DECIMAL(7,2)
);

-- ----- web_sales -----
CREATE TABLE web_sales (
    ws_sold_date_sk              BIGINT,
    ws_sold_time_sk              BIGINT,
    ws_ship_date_sk              BIGINT,
    ws_item_sk                   BIGINT,
    ws_bill_customer_sk          BIGINT,
    ws_bill_cdemo_sk             BIGINT,
    ws_bill_hdemo_sk             BIGINT,
    ws_bill_addr_sk              BIGINT,
    ws_ship_customer_sk          BIGINT,
    ws_ship_cdemo_sk             BIGINT,
    ws_ship_hdemo_sk             BIGINT,
    ws_ship_addr_sk              BIGINT,
    ws_web_page_sk               BIGINT,
    ws_web_site_sk               BIGINT,
    ws_ship_mode_sk              BIGINT,
    ws_warehouse_sk              BIGINT,
    ws_promo_sk                  BIGINT,
    ws_order_number              BIGINT,
    ws_quantity                  BIGINT,
    ws_wholesale_cost            DECIMAL(7,2),
    ws_list_price                DECIMAL(7,2),
    ws_sales_price               DECIMAL(7,2),
    ws_ext_discount_amt          DECIMAL(7,2),
    ws_ext_sales_price           DECIMAL(7,2),
    ws_ext_wholesale_cost        DECIMAL(7,2),
    ws_ext_list_price            DECIMAL(7,2),
    ws_ext_tax                   DECIMAL(7,2),
    ws_coupon_amt                DECIMAL(7,2),
    ws_ext_ship_cost             DECIMAL(7,2),
    ws_net_paid                  DECIMAL(7,2),
    ws_net_paid_inc_tax          DECIMAL(7,2),
    ws_net_paid_inc_ship         DECIMAL(7,2),
    ws_net_paid_inc_ship_tax     DECIMAL(7,2),
    ws_net_profit                DECIMAL(7,2)
);

-- ----- web_returns -----
CREATE TABLE web_returns (
    wr_returned_date_sk          BIGINT,
    wr_returned_time_sk          BIGINT,
    wr_item_sk                   BIGINT,
    wr_refunded_customer_sk      BIGINT,
    wr_refunded_cdemo_sk         BIGINT,
    wr_refunded_hdemo_sk         BIGINT,
    wr_refunded_addr_sk          BIGINT,
    wr_returning_customer_sk     BIGINT,
    wr_returning_cdemo_sk        BIGINT,
    wr_returning_hdemo_sk        BIGINT,
    wr_returning_addr_sk         BIGINT,
    wr_web_page_sk               BIGINT,
    wr_reason_sk                 BIGINT,
    wr_order_number              BIGINT,
    wr_return_quantity           BIGINT,
    wr_return_amt                DECIMAL(7,2),
    wr_return_tax                DECIMAL(7,2),
    wr_return_amt_inc_tax        DECIMAL(7,2),
    wr_fee                       DECIMAL(7,2),
    wr_return_ship_cost          DECIMAL(7,2),
    wr_refunded_cash             DECIMAL(7,2),
    wr_reversed_charge           DECIMAL(7,2),
    wr_account_credit            DECIMAL(7,2),
    wr_net_loss                  DECIMAL(7,2)
);

-- ----- catalog_sales -----
CREATE TABLE catalog_sales (
    cs_sold_date_sk              BIGINT,
    cs_sold_time_sk              BIGINT,
    cs_ship_date_sk              BIGINT,
    cs_bill_customer_sk          BIGINT,
    cs_bill_cdemo_sk             BIGINT,
    cs_bill_hdemo_sk             BIGINT,
    cs_bill_addr_sk              BIGINT,
    cs_ship_customer_sk          BIGINT,
    cs_ship_cdemo_sk             BIGINT,
    cs_ship_hdemo_sk             BIGINT,
    cs_ship_addr_sk              BIGINT,
    cs_call_center_sk            BIGINT,
    cs_catalog_page_sk           BIGINT,
    cs_ship_mode_sk              BIGINT,
    cs_warehouse_sk              BIGINT,
    cs_item_sk                   BIGINT,
    cs_promo_sk                  BIGINT,
    cs_order_number              BIGINT,
    cs_quantity                  BIGINT,
    cs_wholesale_cost            DECIMAL(7,2),
    cs_list_price                DECIMAL(7,2),
    cs_sales_price               DECIMAL(7,2),
    cs_ext_discount_amt          DECIMAL(7,2),
    cs_ext_sales_price           DECIMAL(7,2),
    cs_ext_wholesale_cost        DECIMAL(7,2),
    cs_ext_list_price            DECIMAL(7,2),
    cs_ext_tax                   DECIMAL(7,2),
    cs_coupon_amt                DECIMAL(7,2),
    cs_ext_ship_cost             DECIMAL(7,2),
    cs_net_paid                  DECIMAL(7,2),
    cs_net_paid_inc_tax          DECIMAL(7,2),
    cs_net_paid_inc_ship         DECIMAL(7,2),
    cs_net_paid_inc_ship_tax     DECIMAL(7,2),
    cs_net_profit                DECIMAL(7,2)
);

-- ----- catalog_returns -----
CREATE TABLE catalog_returns (
    cr_returned_date_sk          BIGINT,
    cr_returned_time_sk          BIGINT,
    cr_item_sk                   BIGINT,
    cr_refunded_customer_sk      BIGINT,
    cr_refunded_cdemo_sk         BIGINT,
    cr_refunded_hdemo_sk         BIGINT,
    cr_refunded_addr_sk          BIGINT,
    cr_returning_customer_sk     BIGINT,
    cr_returning_cdemo_sk        BIGINT,
    cr_returning_hdemo_sk        BIGINT,
    cr_returning_addr_sk         BIGINT,
    cr_call_center_sk            BIGINT,
    cr_catalog_page_sk           BIGINT,
    cr_ship_mode_sk              BIGINT,
    cr_warehouse_sk              BIGINT,
    cr_reason_sk                 BIGINT,
    cr_order_number              BIGINT,
    cr_return_quantity           BIGINT,
    cr_return_amount             DECIMAL(7,2),
    cr_return_tax                DECIMAL(7,2),
    cr_return_amt_inc_tax        DECIMAL(7,2),
    cr_fee                       DECIMAL(7,2),
    cr_return_ship_cost          DECIMAL(7,2),
    cr_refunded_cash             DECIMAL(7,2),
    cr_reversed_charge           DECIMAL(7,2),
    cr_store_credit              DECIMAL(7,2),
    cr_net_loss                  DECIMAL(7,2)
);
