"""
setup_tpcds.py
==============
Phase 3B: TPC-DS data generation + PostgreSQL load.

Same recipe as setup_tpch.py:

    1. DuckDB's `tpcds` extension generates data at SF (default 0.1).
    2. DuckDB introspects its own schema and emits PG-compatible DDL
       into  db/tpcds_schema.sql  (regenerated on every run).
    3. CSVs are exported to data/tpcds/raw_data/.
    4. PG creates the schema and bulk-loads via COPY.
    5. ANALYZE refreshes planner statistics.

Why generate the schema dynamically?
    The TPC-DS schema has 24 tables and ~430 columns. Hand-writing
    PG-compatible DDL is error-prone; introspecting DuckDB's already-
    correct schema and translating types is reliable.

Default scale factor is 0.1 (≈100 MB) so the load completes in a
couple of minutes on a laptop. Pass --sf 1 for the canonical SF=1
(~1 GB, comparable to TPC-H SF=1).
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path
from typing import Iterable

import duckdb
import psycopg2

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from config.db_config import DB_CONFIG  # noqa: E402

SCHEMA_FILE = PROJECT_ROOT / "db" / "tpcds_schema.sql"
DATA_DIR    = PROJECT_ROOT / "data" / "tpcds" / "raw_data"

# TPC-DS table names in the order DuckDB's tpcds extension creates them.
# We load fact tables LAST so foreign keys resolve cleanly even if we
# ever add FK constraints.
TPCDS_TABLES: tuple[str, ...] = (
    "income_band",
    "ship_mode",
    "reason",
    "warehouse",
    "promotion",
    "household_demographics",
    "customer_demographics",
    "customer_address",
    "date_dim",
    "time_dim",
    "item",
    "web_site",
    "web_page",
    "store",
    "call_center",
    "catalog_page",
    "customer",
    "inventory",
    "store_sales",
    "store_returns",
    "web_sales",
    "web_returns",
    "catalog_sales",
    "catalog_returns",
)


# ---------------------------------------------------------------------------
# DuckDB → PG type translation
# ---------------------------------------------------------------------------
def _pg_type(duck_type: str) -> str:
    t = duck_type.upper()
    if t.startswith("DECIMAL"):
        return duck_type
    if t in ("INTEGER", "INT", "INT4"):
        return "INTEGER"
    if t in ("BIGINT", "INT8"):
        return "BIGINT"
    if t in ("HUGEINT",):
        return "NUMERIC(38,0)"
    if t in ("DATE",):
        return "DATE"
    if t in ("TIMESTAMP", "TIMESTAMP_NS", "TIMESTAMP_MS", "TIMESTAMP_S"):
        return "TIMESTAMP"
    if t in ("VARCHAR", "TEXT"):
        return "TEXT"
    if t.startswith("CHAR"):
        return duck_type
    if t in ("BOOLEAN",):
        return "BOOLEAN"
    if t in ("FLOAT", "REAL"):
        return "REAL"
    if t in ("DOUBLE",):
        return "DOUBLE PRECISION"
    return duck_type


def _emit_schema_sql(con) -> str:
    """Introspect DuckDB and produce a PG-compatible schema DDL string."""
    lines: list[str] = [
        "-- ==========================================================",
        "-- TPC-DS schema for PostgreSQL (auto-generated by setup_tpcds.py)",
        "-- DO NOT edit by hand — re-run the setup script.",
        "-- ==========================================================",
        "-- Namespaced under the `tpcds` schema so the shared `customer`",
        "-- table name never collides with TPC-H (which lives in `tpch`).",
        "CREATE SCHEMA IF NOT EXISTS tpcds;",
        "SET search_path TO tpcds;",
        "",
    ]
    # Drop in reverse so child-first.
    for t in reversed(TPCDS_TABLES):
        lines.append(f"DROP TABLE IF EXISTS tpcds.{t} CASCADE;")
    lines.append("")

    for table in TPCDS_TABLES:
        cols = con.execute(f"DESCRIBE {table}").fetchall()
        if not cols:
            raise RuntimeError(f"DuckDB has no schema for table {table}")
        lines.append(f"-- ----- {table} -----")
        lines.append(f"CREATE TABLE tpcds.{table} (")
        col_lines = []
        for row in cols:
            cname, ctype = row[0], row[1]
            col_lines.append(f"    {cname:<28} {_pg_type(ctype)}")
        lines.append(",\n".join(col_lines))
        lines.append(");")
        lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Pipeline steps
# ---------------------------------------------------------------------------
def generate_data_and_schema(sf: float, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"[i] Generating TPC-DS data at SF={sf} via DuckDB ...")

    t0 = time.perf_counter()
    con = duckdb.connect(":memory:")
    con.execute("INSTALL tpcds;")
    con.execute("LOAD tpcds;")
    con.execute(f"CALL dsdgen(sf={sf});")

    schema_sql = _emit_schema_sql(con)
    SCHEMA_FILE.write_text(schema_sql, encoding="utf-8")
    print(f"    wrote PG schema -> {SCHEMA_FILE.relative_to(PROJECT_ROOT)}")

    for table in TPCDS_TABLES:
        csv_path = out_dir / f"{table}.csv"
        con.execute(
            f"COPY {table} TO '{csv_path.as_posix()}' "
            f"(HEADER, DELIMITER '|', FORMAT csv)"
        )
        size_mb = csv_path.stat().st_size / (1024 * 1024)
        print(f"    exported {table:<24} -> {csv_path.name}  ({size_mb:.1f} MB)")

    con.close()
    print(f"[OK] DuckDB generation finished in {time.perf_counter() - t0:.1f}s\n")


def apply_schema(conn) -> None:
    print(f"[i] Applying schema from {SCHEMA_FILE.relative_to(PROJECT_ROOT)} ...")
    sql = SCHEMA_FILE.read_text(encoding="utf-8")
    with conn.cursor() as cur:
        cur.execute(sql)
    conn.commit()
    print("[OK] Schema created.\n")


def copy_table(conn, table: str, csv_path: Path) -> None:
    if not csv_path.exists():
        raise FileNotFoundError(f"missing {csv_path} — run without --skip-gen first")

    print(f"[*] Loading {table:<24} from {csv_path.name} ...", end="", flush=True)
    t0 = time.perf_counter()
    with csv_path.open("rb") as f, conn.cursor() as cur:
        cur.copy_expert(
            f"COPY tpcds.{table} FROM STDIN WITH "
            f"(FORMAT csv, HEADER true, DELIMITER '|', NULL '')",
            f,
        )
    conn.commit()
    print(f"  done in {time.perf_counter() - t0:.1f}s")


def load_all(conn, data_dir: Path, tables: Iterable[str]) -> None:
    print("[i] Bulk-loading CSVs into PostgreSQL ...")
    for table in tables:
        copy_table(conn, table, data_dir / f"{table}.csv")
    print()


def analyze_all(conn, tables: Iterable[str]) -> None:
    print("[i] Running ANALYZE on TPC-DS tables ...")
    with conn.cursor() as cur:
        for t in tables:
            cur.execute(f"ANALYZE tpcds.{t};")
    conn.commit()
    print("[OK] Statistics refreshed.\n")


# ---------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="TPC-DS setup: generate + load.")
    p.add_argument("--sf", type=float, default=0.1,
                   help="TPC-DS scale factor (default: 0.1 = ~100 MB; use 1 for canonical SF=1)")
    p.add_argument("--skip-gen",  action="store_true",
                   help="reuse existing CSVs in data/tpcds/raw_data/")
    p.add_argument("--skip-load", action="store_true",
                   help="generate CSVs only; do not touch PostgreSQL")
    return p.parse_args()


def main() -> int:
    args = parse_args()

    if not args.skip_gen:
        generate_data_and_schema(args.sf, DATA_DIR)
    else:
        print("[i] --skip-gen: reusing existing CSVs in", DATA_DIR)
        if not SCHEMA_FILE.exists():
            print("[!] schema file missing; run without --skip-gen at least once",
                  file=sys.stderr)
            return 1

    if args.skip_load:
        print("[i] --skip-load: stopping before PostgreSQL load. Done.")
        return 0

    print(
        f"[i] Connecting to postgres://{DB_CONFIG['user']}@"
        f"{DB_CONFIG['host']}:{DB_CONFIG['port']}/{DB_CONFIG['dbname']}"
    )
    try:
        conn = psycopg2.connect(**DB_CONFIG)
    except psycopg2.OperationalError as exc:
        print(f"[!] Could not connect to PostgreSQL: {exc}", file=sys.stderr)
        return 1

    try:
        apply_schema(conn)
        load_all(conn, DATA_DIR, TPCDS_TABLES)
        analyze_all(conn, TPCDS_TABLES)
    finally:
        conn.close()

    print("[OK] TPC-DS setup complete. You can now run:")
    print("    python scripts/collect_tpcds_plans.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
